apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-deployment
  namespace: tp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      labels:
        app: monapp
    spec:
      containers:
      - name: monapp
        image: europe-west9-docker.pkg.dev/420465132868/tp-repo/monapp:1.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: tp-config
        volumeMounts:
        - name: tp-storage
          mountPath: /data
      volumes:
      - name: tp-storage
        persistentVolumeClaim:
          claimName: tp-pvc-rwx